FROM ubuntu:18.04

LABEL maintainer Sky Butter <skybutter@gmail.com>

# snowsql 1.2.x install bash require zip/unzip to run
RUN apt-get update && apt-get --assume-yes install  curl \
    zip unzip

# Create non-root user
RUN groupadd --system snowflake --gid 444 && \
useradd --uid 444 --system --gid snowflake --home-dir /home/snowflake --create-home --shell /sbin/nologin --comment "Docker image user" snowflake && \
chown -R snowflake:snowflake /home/snowflake

# default to being in the user's home directory
WORKDIR /home/snowflake

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
#ENV VERSION 1.1.86
ENV VERSION 1.2.10
ENV SNOWSQL_DEST /usr/local/bin
ENV SNOWSQL_LOGIN_SHELL /home/snowflake/.bashrc

# grab the installation script.  The url is different from version 1.1.x.
RUN curl -o snowsql-${VERSION}-linux_x86_64.bash https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.10-linux_x86_64.bash

# Install the tool
RUN bash snowsql-${VERSION}-linux_x86_64.bash

# Switch to the non-root user
USER snowflake

# Default snowsql config bootstrap log file location is set to wrong location.  Caused an error.
COPY --chown=snowflake config-1.2.10 /home/snowflake/.snowsql/config

# Run the SnowSQL client once, allowing it to auto-upgrade to the latest version.
# See https://docs.snowflake.com/en/user-guide/snowsql-install-config.html#label-understanding-auto-upgrades
RUN snowsql -v

ENTRYPOINT ["snowsql"]

CMD ["-v"]
